trainer:
  max_epochs: 50
  accelerator: mps
  devices: 1
data:
  dataset_name: ^DJI
  seq_len: 30
  label_len: 10
  pred_len: 7
  variate: m
  target: Close
model:
  model:
    class_path: torchts.nn.models.Informer.Informer
    init_args:
      factor: 3
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse