trainer:
  max_epochs: 6
  accelerator: cpu
  devices: 1
data:
  dataset_name: BTC-USD
  seq_len: 120
  label_len: 60
  pred_len: 30
  variate: u
  target: Close
  frequency: d
model:
  model:
    class_path: torchts.nn.models.Informer.Informer
    init_args:
      factor: 3
      mix_attention: TRUE
  learning_rate: 0.0001
  loss: mse
